{% set version = "3.18.0" %}


package:
    name: freeimage
    version: {{ version }}
    # note: also update version in run_test.py

source:
    fn: FreeImage{{ version.replace(".", "") }}.zip
    url: http://downloads.sourceforge.net/freeimage/FreeImage{{ version.replace(".", "") }}.zip
    sha256: f41379682f9ada94ea7b34fe86bf9ee00935a3147be41b6569c9605a53e438fd
    patches:
        - Makefile.osx.patch  # [osx]

build:
    number: 0
    skip: true  # [win and vc<14]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make  # [unix]

test:
    requires:
        - python
    commands:
        - python run_test.py

about:
    home: http://freeimage.sourceforge.net/
    license: GPLv2 and FreeImage Public License
    summary: Helps provide support for many common image formats (PNG, JPEG, TIFF, BMP and others).

extra:
    recipe-maintainers:
        - almarklein
        - jakirkham
        - msarahan
